### ISSUE TITLE
Unable to run pod install and React Native link is throwing warning.

### ISSUE THREAD

**Issue by waqas19921** [joltup/rn-fetch-blob#392] opened 2019-07-01 01:36 UTC
I have used following versions
React Native version = 0.60.0-rc.3
Fetch Blob version = 0.10.15

`react-native link` command is giving following warning on new react-native version 0.60.

<img width="859" alt="Screenshot 2019-07-01 at 6 34 10 AM" src="https://user-images.githubusercontent.com/17469425/60405544-4253d480-9bca-11e9-903c-42718a141504.png">

```
RNFB_ANDROID_PERMISSIONS=true react-native link rn-fetch-blob
warn Package "rn-fetch-blob" is using deprecated "rnpm" config that will stop working from next release. Please notify its maintainers about it.
RNFetchBlob checking app version ..
RNFetchBlob detected app version => 0.6
Add Android permissions => false
RNFetchBlob patching AndroidManifest.xml .. 
RNFetchBlob patching AndroidManifest.xml .. ok
```
## Need to update pod dependencies for new version of react-native.
Here is the stack when i ran pod install
```
[!] CocoaPods could not find compatible versions for pod "React/Core":
  In Podfile:
    rn-fetch-blob (from `../node_modules/rn-fetch-blob`) was resolved to 0.10.6, which depends on
      React/Core

None of your spec sources contain a spec satisfying the dependency: `React/Core`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

[!] Package "rn-fetch-blob" is using deprecated "rnpm" config that will stop working from next release. Please notify its maintainers about it.

```

**Comment by elkinjosetm** [comment] 2019-07-04 19:13
Same issue here, any idea how to fix it?

**Comment by andrewdazs** [comment] 2019-07-05 15:59
The same thing is happening to me. If anyone has any idea how to solve this...

**Comment by Fouppy** [comment] 2019-07-08 12:27
We need to apply https://github.com/Soni96pl/react-native-sound/commit/c8034526893f4f7f5463fa53e0ce5875cfbde845 to https://github.com/joltup/rn-fetch-blob/blob/master/rn-fetch-blob.podspec.

Problem is, the PR will never be merged, AndroidX PR is pending since 01/24 :/

**Comment by RyanThomas73** [comment] 2019-07-08 19:39
I'm going to use [patch-package](https://github.com/ds300/patch-package) to apply Fouppy's fix until, hopefully, there is an update to this dependency.

**Comment by Psiiirus** [comment] 2019-07-09 08:18
> I'm going to use [patch-package](https://github.com/ds300/patch-package) to apply Fouppy's fix until, hopefully, there is an update to this dependency.

nice, that worked for me and i guess it is a quite good workaround while so many the RN60 PRs are still waiting to be merged

**Comment by femiveys** [comment] 2019-07-10 09:48
This is duplicate of https://github.com/joltup/rn-fetch-blob/pull/397

**Comment by Traviskn** [comment] 2019-07-15 00:12
resolved by #397

**Closed by Traviskn** 2019-07-15 00:12 UTC

**Comment by aelarassi** [comment] 2020-09-07 16:12
In Root Directory Run

`grep -rl "s.dependency 'React/Core'" node_modules/ | xargs sed -i '' 's=React/Core=React-Core=g'`

**Comment by devjourney2019** [comment] 2021-09-29 00:14
Cool @aelarassi

**Comment by kundan175** [comment] 2022-10-01 13:52
> In Root Directory Run
> 
> `grep -rl "s.dependency 'React/Core'" node_modules/ | xargs sed -i '' 's=React/Core=React-Core=g'`

Working

**Comment by bekroz** [comment] 2023-07-09 09:49
> 

Thanx for the solution, it's working.

**Comment by bekroz** [comment] 2023-07-09 09:50
> Thanx for the solution, @aelarassi, it's working.

**Comment by bekroz** [comment] 2023-07-09 09:50
> @aelarassi 

Thanx for the solution, it's working.
